# local-chat-radius: radius of local chat channel (in blocks)
# default-channel: default chat channel that new users will join
# default-colour: default new channel colour
# announce-timeouts: announce timeout to the entire server?
# spam:
#     limit: number of messages sent
#     period: within the given time period
# hard channels
local-chat-radius: 200
default-channel: G
default-colour: grey
announce-timeouts: true
spam:
  limit: 5
  period: 3
hard-channels:
  G:
    colour: grey
    alias: g
    permission: global
  L:
    colour: pink
    alias: lo
    permission: local
    local: true
  Broadcast:
    colour: purple
    alias: bc
    permission: broadcast
    broadcast: true
  MOD:
    colour: purple
    alias: m
    permission: mod
  ADMIN:
    colour: green
    alias: a
    permission: admin
